### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by CelesteBlue-dev** [phonorepo/psx-cpl#1]
Hello
I would like to test your app but I can't get the binaries.
May you provide them in the Releases tab please ?
Regards

**Comment by phonorepo** [comment]
If you simply want to try it, I added compiled ones here:
https://github.com/phonorepo/psx-cpl/tree/archive

psx-cpl_light will only work if you have the other dlls already installed.

**Comment by phonorepo** [comment]
Done: https://github.com/phonorepo/psx-cpl/releases
